"use client";
import { useEffect, useSyncExternalStore, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { FinancialCalculator } from '@/lib/financial/financial-plan';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';

export default function ReportPage() {
  const router = useRouter();
  const rawData = useSyncExternalStore(
    () => () => {},
    () => typeof window !== 'undefined' ? localStorage.getItem('advisoryData') : null,
    () => null
  );

  const reportData = useMemo(() => {
    if (!rawData) return null;
    try {
      const data = JSON.parse(rawData) as Record<string, string | number>;
      return { data, financials: FinancialCalculator.calculatePS26091(Number(data.available_margin)) };
    } catch {
      return null;
    }
  }, [rawData]);

  useEffect(() => {
    if (typeof window !== 'undefined' && !rawData) {
      router.push('/advisor');
    }
  }, [rawData, router]);

  if (!reportData) return <div className="p-12 text-center">Loading...</div>;
  const { data, financials } = reportData;

  if (financials.outOfRange) {
    return (
      <div className="p-12 text-center">
        <p className="text-amber-700 font-semibold">Project out of scheme range.</p>
        <Button className="mt-4" onClick={() => router.push('/advisor')}>Go Back</Button>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl bg-white shadow-xl my-8">
      <div className="flex justify-between items-center border-b pb-6 mb-6 print:pb-2 print:mb-4">
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Business Feasibility & Financial Structuring Report</h1>
          <p className="text-slate-500 mt-2">Generated by UdayamAI — PS 26091 Prototype</p>
        </div>
        <Button onClick={() => window.print()} className="print:hidden"><Download className="mr-2 h-4 w-4" /> Download PDF</Button>
      </div>

      <div className="space-y-8 print:space-y-6">
        <section>
          <h2 className="text-xl font-bold border-b pb-2 mb-4">Entrepreneur Profile</h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div><span className="text-slate-500">Location:</span> <span className="font-semibold">{data.location}</span></div>
            <div><span className="text-slate-500">Business Category:</span> <span className="font-semibold">{data.business_category}</span></div>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold border-b pb-2 mb-4">10/90 Financial Structure</h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div><span className="text-slate-500">Available Margin (10%):</span> <span className="font-semibold">₹{financials.availableMargin.toLocaleString()}</span></div>
            <div><span className="text-slate-500">Project Cost (100%):</span> <span className="font-semibold">₹{financials.projectCost.toLocaleString()}</span></div>
            <div><span className="text-slate-500">Requested Loan (90%):</span> <span className="font-semibold">₹{financials.requestedLoan.toLocaleString()}</span></div>
            <div><span className="text-slate-500">Effective Loan (scheme-capped):</span> <span className="font-semibold text-blue-700">₹{financials.effectiveLoan.toLocaleString()}</span></div>
            <div><span className="text-slate-500">Recommended Scheme:</span> <span className="font-semibold">{financials.schemeName}</span></div>
          </div>
          {financials.warningMessage && (
            <p className="mt-3 text-xs text-amber-700 bg-amber-50 p-2 rounded">{financials.warningMessage}</p>
          )}
        </section>

        <section>
          <h2 className="text-xl font-bold border-b pb-2 mb-4">Repayment Terms</h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div><span className="text-slate-500">Interest Rate (p.a.):</span> <span className="font-semibold">{financials.interestRate}%</span></div>
            <div><span className="text-slate-500">Tenure:</span> <span className="font-semibold">{financials.tenureMonths} Months</span></div>
            <div><span className="text-slate-500">Moratorium:</span> <span className="font-semibold">{financials.moratoriumMonths} Months</span></div>
            <div><span className="text-slate-500">Quarterly EMI (post-moratorium):</span> <span className="font-semibold text-blue-700">₹{Math.round(financials.quarterlyPayment).toLocaleString()}</span></div>
            <div><span className="text-slate-500">Total Interest:</span> <span className="font-semibold">₹{Math.round(financials.totalInterest).toLocaleString()}</span></div>
            <div><span className="text-slate-500">Total Repayment:</span> <span className="font-semibold">₹{Math.round(financials.totalRepayment).toLocaleString()}</span></div>
          </div>
        </section>

        <section className="mt-8 text-xs text-slate-400 text-center border-t pt-4">
          Data Disclaimer: This report uses representative prototype estimates and deterministic calculation. It does not constitute guaranteed financial advice. Final loan approval and scheme allocation is subject to verification by authorized institutions.
        </section>
      </div>
    </div>
  );
}
