"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { ChevronDown, ExternalLink, BookOpen, MapPin, Calculator } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

export default function MethodologyPage() {
  const [isMathOpen, setIsMathOpen] = useState(false);

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 md:px-8">
      <div className="max-w-3xl mx-auto space-y-10">
        
        {/* Header */}
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 mb-2">Journey Readiness Methodology</h1>
          <p className="text-slate-600 text-lg">Transparent. Deterministic. Traceable.</p>
        </div>

        {/* Section 1: What this score is — and isn't */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <BookOpen className="h-6 w-6 text-emerald-600" />
            What this score is — and isn't
          </h2>
          <div className="prose prose-slate max-w-none text-slate-700 leading-relaxed">
            <p>
              The UdayamAI Journey Readiness Score is a transparent readiness breakdown evaluating your business profile across three layers: personal/business readiness, financial readiness, and regional context. It is built strictly from published entrepreneurship research and deterministic rules.
            </p>
            <p className="font-semibold text-slate-900 bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg">
              It is NOT a prediction of whether your business will succeed or fail. 
            </p>
            <p>
              No validated dataset exists anywhere in the research literature for predicting success/failure rates specifically for first-generation and marginalized micro-entrepreneurs in India. We will not pretend otherwise by showing you a fake-precise percentage generated by a black-box AI model. This tool exists to highlight <em>where</em> you can strengthen your profile, not to predict your destiny.
            </p>
          </div>
        </section>

        {/* Section 2: The three layers */}
        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-slate-900">The three layers, and what's weighted most</h2>
          <Card className="shadow-sm border-slate-200">
            <CardContent className="p-6">
              
              <div className="flex flex-col md:flex-row h-12 w-full rounded-full overflow-hidden mb-6 shadow-inner">
                <div className="bg-blue-600 flex items-center justify-center text-white text-xs font-bold w-[60%]">Archetype (60%)</div>
                <div className="bg-emerald-500 flex items-center justify-center text-white text-xs font-bold w-[40%]">Financial (40%)</div>
              </div>
              <p className="text-center text-sm text-slate-500 mb-8 font-medium">
                * Final combined score is then adjusted by a ±15% Regional Ecosystem Multiplier
              </p>

              <div className="space-y-6">
                <div>
                  <h3 className="font-bold text-slate-900 text-lg">1. Archetype Layer (60%)</h3>
                  <p className="text-slate-600 text-sm mt-1">
                    Evaluates experience, preparedness, traits, and background. 
                    <br/><br/>
                    <strong>Why preparedness overrides raw experience:</strong> This platform is built for first-generation entrepreneurs. A model that rewarded prior experience most heavily would unfairly penalize exactly the people it's meant to help. Therefore, structured planning and preparedness carry higher weights.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 text-lg">2. Financial Layer (40%)</h3>
                  <p className="text-slate-600 text-sm mt-1">
                    Determines if your project scale matches government scheme realities and your available margin capital.
                  </p>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 text-lg">3. Regional Context (±15%)</h3>
                  <p className="text-slate-600 text-sm mt-1">
                    Adjusts expectations based on the structural reality (infrastructure, culture) of your state.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        {/* Section 3: The research this is built on */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900">The research this is built on</h2>
          <div className="grid gap-4">
            
            <Card className="hover:shadow-md transition-shadow">
              <CardContent className="p-4 flex flex-col md:flex-row gap-4 justify-between items-start">
                <div>
                  <h3 className="font-bold text-slate-800">Lussier (1995) non-financial SME prediction model</h3>
                  <p className="text-sm text-slate-600 mt-1">
                    Original 15 variables: capital adequacy, record-keeping/financial control, industry experience, management experience, business/strategic planning, professional advisor use, higher education, staffing adequacy, product/service timing, economic timing, age of owner, partnership vs. sole ownership, parents owned a business, minority ownership status, marketing skill.
                  </p>
                </div>
                <a href="https://doi.org/10.1111/j.1540-627X.1995.tb00394.x" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 font-mono bg-blue-50 px-2 py-1 rounded shrink-0 hover:bg-blue-100 hover:underline inline-flex items-center gap-1">1995 Study <ExternalLink className="h-3 w-3"/></a>
              </CardContent>
            </Card>

            <Card className="hover:shadow-md transition-shadow">
              <CardContent className="p-4 flex flex-col md:flex-row gap-4 justify-between items-start">
                <div>
                  <h3 className="font-bold text-slate-800">The Indian women-MSME entrepreneurship study (DOAJ, 2025, n=700)</h3>
                  <p className="text-sm text-slate-600 mt-1">
                    Determinants of entrepreneurial success among 700 Indian women MSME entrepreneurs (PLS-SEM). Found that need for achievement, risk-taking propensity, self-confidence, financial factors, and socio-cultural factors all significantly and positively predict entrepreneurial success.
                  </p>
                </div>
                <a href="https://scholar.google.com/scholar?q=Determinants+influencing+the+entrepreneurial+success+of+MSMEs+in+emerging+economies%3A+a+study+of+Indian+women+entrepreneurs" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 font-mono bg-blue-50 px-2 py-1 rounded shrink-0 hover:bg-blue-100 hover:underline inline-flex items-center gap-1">DOAJ, 2025 <ExternalLink className="h-3 w-3"/></a>
              </CardContent>
            </Card>

            <Card className="hover:shadow-md transition-shadow">
              <CardContent className="p-4 flex flex-col md:flex-row gap-4 justify-between items-start">
                <div>
                  <h3 className="font-bold text-slate-800">Roy (2023) AHP-TOPSIS SME credit scoring methodology</h3>
                  <p className="text-sm text-slate-600 mt-1">
                    A credit scoring model for SMEs using AHP and TOPSIS. Built specifically because regression models don't perform well with limited data points and missing data. Proposes a 3-stage process converting expert judgment into proxy risk-score labels.
                  </p>
                </div>
                <a href="https://doi.org/10.1002/ijfe.2425" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 font-mono bg-blue-50 px-2 py-1 rounded shrink-0 hover:bg-blue-100 hover:underline inline-flex items-center gap-1">Int. J. Finance & Economics <ExternalLink className="h-3 w-3"/></a>
              </CardContent>
            </Card>

            <Card className="hover:shadow-md transition-shadow">
              <CardContent className="p-4 flex flex-col md:flex-row gap-4 justify-between items-start">
                <div>
                  <h3 className="font-bold text-slate-800">Saaty's Analytic Hierarchy Process methodology</h3>
                  <p className="text-sm text-slate-600 mt-1">
                    Provides the mathematical foundation for the deterministic scoring engine.
                    Decomposes the decision into a hierarchy, gets pairwise comparisons for relative importance, and computes consistency-checked weights.
                  </p>
                </div>
                <a href="https://doi.org/10.1016/0377-2217(90)90057-I" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 font-mono bg-blue-50 px-2 py-1 rounded shrink-0 hover:bg-blue-100 hover:underline inline-flex items-center gap-1">Saaty, 1977/1980 <ExternalLink className="h-3 w-3"/></a>
              </CardContent>
            </Card>

            <Card className="hover:shadow-md transition-shadow">
              <CardContent className="p-4 flex flex-col md:flex-row gap-4 justify-between items-start">
                <div>
                  <h3 className="font-bold text-slate-800">Regional entrepreneurial ecosystem quality index research</h3>
                  <p className="text-sm text-slate-600 mt-1">
                    Research strongly predicts venture survival and prevalence of high-growth firms in a region based on 5 dimensions: supportive entrepreneurial culture, access to finance, human capital, innovation capacity, and formal institutions.
                  </p>
                </div>
                <a href="https://scholar.google.com/scholar?q=Regional+entrepreneurial+ecosystem+quality+index" target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 font-mono bg-blue-50 px-2 py-1 rounded shrink-0 hover:bg-blue-100 hover:underline inline-flex items-center gap-1">Configurational studies 2023–2025 <ExternalLink className="h-3 w-3"/></a>
              </CardContent>
            </Card>

          </div>
        </section>

        {/* Section 4: Regional data sources */}
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <MapPin className="h-6 w-6 text-blue-500" />
            Regional data sources
          </h2>
          <Card className="shadow-sm border-slate-200 bg-slate-50/50">
            <CardContent className="p-6">
              <p className="text-sm text-slate-600 mb-4 bg-white p-3 rounded border border-slate-200">
                <strong>Data Integration Note:</strong> The current layer 3 calculations utilize <em>representative seed values</em> derived from the sources below for prototype demonstration. Live-fetching APIs are architected but not currently active.
              </p>
              <ul className="space-y-3">
                <li>
                  <a href="https://data.gov.in" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-blue-600 hover:underline font-medium">
                    Udyam Registration district-level data <ExternalLink className="h-3 w-3" />
                  </a>
                </li>
                <li>
                  <a href="https://indiaai.gov.in" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-blue-600 hover:underline font-medium">
                    District-level manufacturing MSME data (AIKosh/IndiaAI) <ExternalLink className="h-3 w-3" />
                  </a>
                </li>
                <li>
                  <a href="https://www.startupindia.gov.in" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-blue-600 hover:underline font-medium">
                    DPIIT State Startup Ranking <ExternalLink className="h-3 w-3" />
                  </a>
                </li>
                <li>
                  <a href="https://niti.gov.in" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-blue-600 hover:underline font-medium">
                    NITI Aayog India Innovation Index <ExternalLink className="h-3 w-3" />
                  </a>
                </li>
              </ul>
            </CardContent>
          </Card>
        </section>

        {/* Section 5: The math */}
        <section className="space-y-4">
          <div className="border border-slate-200 rounded-lg bg-white shadow-sm overflow-hidden">
            <button onClick={() => setIsMathOpen(!isMathOpen)} className="w-full p-4 flex items-center justify-between bg-slate-50 hover:bg-slate-100 transition-colors">
              <div className="flex items-center gap-2">
                <Calculator className="h-5 w-5 text-slate-700" />
                <span className="font-bold text-slate-900">The math, for anyone who wants to check it</span>
              </div>
              <ChevronDown className={`h-5 w-5 text-slate-500 transition-transform duration-200 ${isMathOpen ? 'rotate-180' : ''}`} />
            </button>
            {isMathOpen && (
            <div className="p-6 border-t border-slate-200 bg-white">
              <div className="space-y-6">
                <p className="text-sm text-slate-600">
                  Below are the Analytic Hierarchy Process (AHP) pairwise comparison matrices and consistency checks used to derive the weights for Layer 1.
                </p>
                
                
                <div className="space-y-4">
                  <div className="p-4 bg-emerald-50 border border-emerald-200 rounded text-emerald-800 text-sm">
                    <strong>Consistency Check Verified:</strong> All five pairwise comparison matrices (1 top-level 4×4 matrix plus 4 sub-criteria matrices) passed the standard Saaty principal eigenvector consistency check with a Consistency Ratio <strong>(CR) &lt; 0.10</strong>.
                  </div>
                  <h4 className="font-semibold text-slate-800">Derived Category Weights (Level 1)</h4>
                  <ul className="list-disc pl-5 text-sm text-slate-700 space-y-1">
                    <li><strong>Preparedness &amp; Process:</strong> 0.4729</li>
                    <li><strong>Psychological/Entrepreneurial Traits:</strong> 0.2844</li>
                    <li><strong>Experience &amp; Human Capital:</strong> 0.1699</li>
                    <li><strong>Background:</strong> 0.0729</li>
                  </ul>
                  <p className="text-xs text-slate-500 mt-4 italic">
                    Note: The raw 4x4 matrix derivations generate the weights used deterministically in the UdayamAI engine.
                  </p>
                </div>

              </div>
            </div>
            )}
          </div>
        </section>

        {/* Footer */}
        <footer className="mt-16 pt-8 border-t border-slate-200 text-center">
          <p className="text-sm text-slate-500 font-medium px-4">
            UdayamAI uses intelligent assistance to provide personalized guidance. Scheme eligibility and financial calculations are determined using configurable rules and verified data.
          </p>
        </footer>

      </div>
    </div>
  );
}
